import { FieldMapKey } from '@formalizer/react-form';

export type DnDAccept = Record<FieldMapKey, string | string[]>;

export const dndAccept: DnDAccept = {
  array: [
    'array',
    'boolean',
    'color',
    'date',
    'dateTime',
    'email',
    'grid',
    'longtext',
    'month',
    'number',
    'object',
    'password',
    'radio',
    'telephone',
    'text',
    'time',
    'week',
  ],
  boolean: 'none',
  color: 'none',
  date: 'none',
  dateTime: 'none',
  email: 'none',
  grid: [
    'array',
    'boolean',
    'color',
    'date',
    'dateTime',
    'email',
    'grid',
    'group',
    'longtext',
    'month',
    'number',
    'object',
    'password',
    'radio',
    'telephone',
    'text',
    'time',
    'week',
  ],
  group: [
    'array',
    'boolean',
    'color',
    'date',
    'dateTime',
    'email',
    'grid',
    'group',
    'longtext',
    'month',
    'number',
    'object',
    'password',
    'radio',
    'telephone',
    'text',
    'time',
    'week',
  ],
  longtext: 'none',
  month: 'none',
  number: 'none',
  object: [
    'array',
    'boolean',
    'color',
    'date',
    'dateTime',
    'email',
    'grid',
    'group',
    'longtext',
    'month',
    'number',
    'object',
    'password',
    'radio',
    'telephone',
    'text',
    'time',
    'week',
  ],
  password: 'none',
  radio: 'radioItem',
  radioItem: 'none',
  string: 'none',
  telephone: 'none',
  text: 'none',
  time: 'none',
  week: 'none',
};
